[project]
name = "reinforcement-learning-basics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Flashness123", email = "lukas.kouba.de@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "gymnasium>=1.3.0",
]

[project.scripts]
reinforcement-learning-basics = "reinforcement_learning_basics:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
